# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nowctl < Formula
  desc "Cross-platform command-line interface for ServiceNow"
  homepage "https://github.com/karastoyanov/NowControl"
  version "0.3.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/karastoyanov/NowControl/releases/download/v0.3.1/nowctl_0.3.1_darwin_amd64.tar.gz"
      sha256 "83e013a112af13302a6183c0242f8ccf658d560c96e2e8d271fe5d876bb27a7f"

      define_method(:install) do
        bin.install "nowctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/karastoyanov/NowControl/releases/download/v0.3.1/nowctl_0.3.1_darwin_arm64.tar.gz"
      sha256 "6e0588950dd92b33c6b8c6b937248986a24b454c634dc6c05a0a169d9d6f62af"

      define_method(:install) do
        bin.install "nowctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/karastoyanov/NowControl/releases/download/v0.3.1/nowctl_0.3.1_linux_amd64.tar.gz"
      sha256 "a37513ae04f8b4765010cd9fdca26273bd545b44f9f258cb388854ffb2e8ca88"
      define_method(:install) do
        bin.install "nowctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/karastoyanov/NowControl/releases/download/v0.3.1/nowctl_0.3.1_linux_arm64.tar.gz"
      sha256 "4bc1053963c0a348c4908e39a865f3c4d5a562d478b78d8e9c0ff8ece48a174b"
      define_method(:install) do
        bin.install "nowctl"
      end
    end
  end

  test do
    system "#{bin}/nowctl --version"
  end
end
